spring:
  config:
    activate:
      on-profile: prod
  #      import: optional:file:.env[.properties]
  output:
    ansi:
      enabled: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false

  datasource:
    url: ${AWS_DATASOURCE_URL}
    username: ${AWS_DATABASE_USERNAME}
    password: ${AWS_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ${AWS_REGION_NAME}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET_NAME}
      upload-path: ${S3_IMAGE_PATH}