name: omocha-dev

networks:
  backend:
    driver: bridge

services:
  omocha:
    image: kwlim1120ss/omocha
    container_name: omocha
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${AWS_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${AWS_DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${AWS_DATABASE_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
      TZ: "Asia/Seoul"
    env_file:
      - .env
    volumes:
      - ${POSTGRES_HOME_DIR}/data:/var/lib/postgresql/data # ${POSTGRES_HOME_DIR}/data
    networks:
      - backend

  database:
    image: postgres:16.4
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - TZ=Asia/Seoul
    env_file:
      - .env
    volumes:
      - ${POSTGRES_HOME_DIR}/data:/var/lib/postgresql/data # ${POSTGRES_HOME_DIR}/data
    networks:
      - backend