def jarName = "omocha-api.jar"

dependencies {
    implementation project(':omocha-domain')
    implementation project(':omocha-infrastructure')

    // java 8 date module added
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.15.2'

}

bootJar {
    enabled = true
}

jar {
    enabled = false
}

tasks.named("bootJar") {
    bootJar.getArchiveFileName().set(jarName) // JAR 이름 설정

    doLast {
        copy {
            from "build/libs/$jarName" // 생성된 JAR 파일 경로
            into "../build/libs" // 복사할 경로
        }
    }
}