def jarName = "omocha-api.jar"

dependencies {
    implementation project(':omocha-core')
    implementation project(':omocha-domain')
}

bootJar {
    enabled = true
}

jar {
    enabled = false
}

tasks.named("bootJar") {
    bootJar.getArchiveFileName().set(jarName) // JAR 이름 설정

    doLast {
        copy {
            from "build/libs/$jarName" // 생성된 JAR 파일 경로
            into "../build/libs" // 복사할 경로
        }
    }
}