-- V1.0.1__init.sql (초기 세팅)

-- 1. answer 테이블 생성
CREATE TABLE IF NOT EXISTS public.answer (
                                             deleted boolean DEFAULT false NOT NULL,
                                             answer_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             created_at timestamp(6) without time zone,
    question_id bigint,
    updated_at timestamp(6) without time zone,
    content character varying(255),
    title character varying(255),
    CONSTRAINT answer_question_id_key UNIQUE (question_id)
    );

-- 2. auction 테이블 생성
CREATE TABLE IF NOT EXISTS public.auction (
                                              auction_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              bid_count bigint,
                                              bid_unit bigint,
                                              created_at timestamp(6) without time zone,
    end_date timestamp(6) without time zone,
    instant_buy_price bigint,
    like_count bigint NOT NULL,
    member_id bigint,
    now_price bigint,
    start_date timestamp(6) without time zone,
    start_price bigint,
    updated_at timestamp(6) without time zone,
    auction_status character varying(255),
    content text,
    thumbnail_path character varying(255),
    title character varying(255),
    CONSTRAINT auction_auction_status_check CHECK (
                                              auction_status IN ('PREBID', 'BIDDING', 'NO_BIDS', 'CONCLUDED', 'COMPLETED')
    )
    );

-- 3. auction_category 테이블 생성
CREATE TABLE IF NOT EXISTS public.auction_category (
                                                       auction_category_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                       auction_id bigint,
                                                       category_id bigint
);

-- 4. bid 테이블 생성
CREATE TABLE IF NOT EXISTS public.bid (
                                          bid_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          auction_id bigint,
                                          bid_price bigint,
                                          buyer_member_id bigint,
                                          created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone
    );

-- 5. category 테이블 생성
CREATE TABLE IF NOT EXISTS public.category (
                                               category_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               parent_id bigint,
                                               name character varying(255)
    );

-- 6. chat 테이블 생성
CREATE TABLE IF NOT EXISTS public.chat (
                                           chat_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           created_at timestamp(6) without time zone,
    room_id bigint,
    sender_member_id bigint,
    updated_at timestamp(6) without time zone,
    message character varying(255),
    message_type character varying(255),
    CONSTRAINT chat_message_type_check CHECK (
                                                 message_type IN ('ENTER', 'CHAT', 'LEAVE')
    )
    );

-- 7. chatroom 테이블 생성
CREATE TABLE IF NOT EXISTS public.chatroom (
                                               room_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               auction_id bigint,
                                               buyer_member_id bigint,
                                               created_at timestamp(6) without time zone,
    seller_member_id bigint,
    updated_at timestamp(6) without time zone,
    room_name character varying(255)
    );

-- 8. conclude 테이블 생성
CREATE TABLE IF NOT EXISTS public.conclude (
                                               conclude_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               auction_id bigint,
                                               buyer_member_id bigint,
                                               conclude_price bigint,
                                               concluded_at timestamp(6) without time zone,
    CONSTRAINT conclude_auction_id_key UNIQUE (auction_id)
    );

-- 9. image 테이블 생성
CREATE TABLE IF NOT EXISTS public.image (
                                            image_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            auction_id bigint,
                                            file_name character varying(255),
    image_path character varying(255)
    );

-- 10. likes 테이블 생성
CREATE TABLE IF NOT EXISTS public.likes (
                                            likes_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            auction_id bigint,
                                            created_at timestamp(6) without time zone,
    member_id bigint,
    CONSTRAINT likes_uk UNIQUE (auction_id, member_id)
    );

-- 11. member 테이블 생성
CREATE TABLE IF NOT EXISTS public.member (
                                             member_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             average_rating double precision,
                                             created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    birth date,
    email character varying(255),
    member_status character varying(255),
    nickname character varying(255),
    password character varying(255),
    phone_number character varying(255),
    profile_image_url character varying(255),
    provider character varying(255),
    provider_id character varying(255),
    role character varying(255),
    username character varying(255),
    CONSTRAINT member_member_status_check CHECK (
                                                    member_status IN ('ACTIVATE', 'DEACTIVATE')
    ),
    CONSTRAINT member_role_check CHECK (
                                           role IN ('ROLE_ADMIN', 'ROLE_USER')
    )
    );

-- 12. question 테이블 생성
CREATE TABLE IF NOT EXISTS public.question (
                                               question_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               deleted boolean DEFAULT false NOT NULL,
                                               auction_id bigint NOT NULL,
                                               created_at timestamp(6) without time zone,
    member_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    content character varying(255),
    title character varying(255)
    );

-- 13. review 테이블 생성
CREATE TABLE IF NOT EXISTS public.review (
                                             review_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             rating double precision,
                                             auction_id bigint,
                                             created_at timestamp(6) without time zone,
    recipient_member_id bigint,
    reviewer_member_id bigint,
    updated_at timestamp(6) without time zone,
    content character varying(255),
    review_type character varying(255),
    CONSTRAINT review_review_type_check CHECK (
                                                  review_type IN ('SELL_REVIEW', 'BUY_REVIEW')
    )
    );
